# Generated by Django 6.0.5 on 2026-09-06 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("rating_changed", "Rating changed"),
                            ("rank_changed", "Rank changed"),
                            ("contest_started", "Contest started"),
                            ("contest_ended", "Contest finished"),
                            ("contest_starting_soon", "Contest starting soon"),
                            ("new_problem", "New problem"),
                            ("report_resolved", "Report reviewed"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "dedup_key",
                    models.CharField(
                        help_text="Event stamp this notification was born from. Together with (user, type) it is the uniqueness key, so a task that runs twice cannot deliver the same event twice.",
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.CharField(max_length=500)),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Internal relative path (/problems/12), or empty when the target is gone and the row should not be clickable.",
                        max_length=255,
                    ),
                ),
                (
                    "seen_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the row was seen in the feed. NULL is what the unread counter counts.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "seen_at"],
                        name="notificatio_user_id_1c048e_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_05b4bc_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "type", "dedup_key"),
                        name="uniq_notification_dedup",
                    )
                ],
            },
        ),
    ]
