# Generated by Django 6.0.5 on 2026-06-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0002_contestscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="subtitle",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="contestscore",
            name="rating_after",
            field=models.IntegerField(
                blank=True,
                help_text="User's rating after this contest (filled by the ELO flow).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contestscore",
            name="rating_delta",
            field=models.IntegerField(
                blank=True,
                help_text="Net rating change for this contest (filled by the ELO flow).",
                null=True,
            ),
        ),
    ]
