# Generated by Django 6.0.5 on 2026-06-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0003_contest_subtitle_contestscore_rating_after_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="rating_applied",
            field=models.BooleanField(
                default=False,
                help_text="Whether ELO ratings have been awarded for this contest.",
            ),
        ),
    ]
