# Generated by Django 6.0.5 on 2026-08-12 19:43

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0004_contest_rating_applied"),
        ("problems", "0005_problem_problem_title_trgm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # gin_trgm_ops needs the pg_trgm extension enabled first.
        ("users", "0008_trigram_extension"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contest",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="contest_title_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
