# Generated by Django 6.0.5 on 2026-08-12 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0005_contest_contest_title_trgm"),
        ("problems", "0006_problem_problem_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contest",
            index=models.Index(
                fields=["end_time", "rating_applied"], name="contest_end_rating"
            ),
        ),
        migrations.AddIndex(
            model_name="contestscore",
            index=models.Index(
                fields=["contest", "-score", "penalty", "last_ac_at"],
                name="cscore_leaderboard",
            ),
        ),
    ]
