# Generated by Django 6.0.5 on 2026-06-27 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0002_tag_problem_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        help_text="PROTECT: a problem that was ever a daily challenge can't be deleted, so past streaks stay intact.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_assignments",
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
