# Generated by Django 6.0.5 on 2026-08-12 19:43

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0004_problem_constraints_problem_input_format_and_more"),
        # gin_trgm_ops needs the pg_trgm extension enabled first.
        ("users", "0008_trigram_extension"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="problem",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="problem_title_trgm", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
