# Generated by Django 6.0.5 on 2026-08-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0005_problem_problem_title_trgm"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(fields=["created_at"], name="problem_created_at"),
        ),
    ]
