# Generated by Django 6.0.5 on 2026-08-19 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('problems', '0006_problem_problem_created_at'),
        ("problems", "0004_problem_constraints_problem_input_format_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem_title",
                    models.CharField(
                        help_text="Snapshot of the problem's title at submission time. Not updated on rename, and stays readable after the problem is deleted.",
                        max_length=255,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("statement", "Mistake in the statement"),
                            ("wrong_test", "Wrong test"),
                            ("wrong_limits", "Wrong limits"),
                            ("improvement", "Suggest an improvement"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "problem",
                    models.ForeignKey(
                        blank=True,
                        help_text="SET_NULL: deleting the problem must not delete the report that documents what was wrong with it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="problems.problem",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_problem_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="problem_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "problem", "status"],
                        name="problems_pr_user_id_6682a2_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="problems_pr_status_1e0694_idx",
                    ),
                ],
            },
        ),
    ]
