# Generated by Django 6.0.5 on 2026-08-27 16:56

from django.db import migrations, models


def unhide_existing_problems(apps, schema_editor):
    """Keep the catalog as it was: only problems added from now on start hidden."""
    Problem = apps.get_model("problems", "Problem")
    Problem.objects.update(is_hidden=False)


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0006_problem_problem_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="is_hidden",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Hidden problems stay out of the public catalog. New problems "
                    "start hidden; a problem is unhidden automatically once a "
                    "contest that uses it has finished."
                ),
            ),
        ),
        migrations.RunPython(unhide_existing_problems, migrations.RunPython.noop),
    ]
