# Generated by Django 6.0.5 on 2026-09-17 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0006_contest_contest_end_rating_and_more"),
        ("problems", "0008_problemreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemreport",
            name="contest",
            field=models.ForeignKey(
                blank=True,
                help_text="The round the report was filed from; empty for the catalog. SET_NULL: deleting the contest must not delete the report.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="problem_reports",
                to="contests.contest",
            ),
        ),
    ]
