# Generated by Django 6.0.5 on 2026-06-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0002_contestscore"),
        ("users", "0002_alter_user_elo_rating_elohistory"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="elohistory",
            index=models.Index(
                fields=["user", "timestamp"], name="users_elohi_user_id_7b585f_idx"
            ),
        ),
    ]
