# Generated by Django 6.0.5 on 2026-06-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_elo_rating_elohistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="max_rating",
            field=models.IntegerField(default=1200),
        ),
    ]
