# Generated by Django 6.0.5 on 2026-06-25 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_slim_elohistory_for_sparkline"),
        ("users", "0003_user_max_rating"),
    ]

    operations = []
