# Generated by Django 6.0.5 on 2026-07-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_merge_20260625_1128"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="elo_rating",
            field=models.IntegerField(db_index=True, default=1200),
        ),
        migrations.AlterField(
            model_name="user",
            name="max_rating",
            field=models.IntegerField(db_index=True, default=1200),
        ),
    ]
