# Generated by Django 6.0.5 on 2026-08-12 19:43

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0008_trigram_extension"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["username"],
                name="user_username_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
