# Generated by Django 6.0.5 on 2026-09-13 12:39

import apps.users.models
from django.db import migrations, models


def replace_null_user_profile_fields(apps, schema_editor):
    User = apps.get_model("users", "User")

    User.objects.filter(avatar__isnull=True).update(avatar="")
    User.objects.filter(avatar_thumb__isnull=True).update(avatar_thumb="")
    User.objects.filter(bio__isnull=True).update(bio="")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_options_user_user_username_trgm"),
    ]

    operations = [
        migrations.RunPython(
            replace_null_user_profile_fields,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to=apps.users.models.user_avatar_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_thumb",
            field=models.ImageField(
                blank=True,
                default="",
                upload_to=apps.users.models.user_avatar_thumb_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
    ]
