# Generated by Django 6.0.5 on 2026-05-18 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contests", "0001_initial"),
        ("problems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                (
                    "language",
                    models.CharField(choices=[("python", "Python")], max_length=20),
                ),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "Accepted"),
                            ("WA", "Wrong Answer"),
                            ("TLE", "Time Limit Exceeded"),
                            ("MLE", "Memory Limit Exceeded"),
                            ("RE", "Runtime Error"),
                            ("CE", "Compilation Error"),
                        ],
                        default=None,
                        help_text="Null until judge processes the submission.",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "execution_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Execution time in milliseconds.",
                        null=True,
                    ),
                ),
                (
                    "memory_used",
                    models.PositiveIntegerField(
                        blank=True, help_text="Memory used in megabytes.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="contests.contest",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="problems.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
