# Generated by Django 6.0.5 on 2026-06-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0003_submission_submissions_user_id_6a1f53_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="error_message",
            field=models.TextField(
                blank=True,
                help_text="Internal judge error message if the run failed before a verdict.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="stderr",
            field=models.TextField(
                blank=True,
                help_text="Captured stderr of the user's program (RE/CE diagnostics).",
                null=True,
            ),
        ),
    ]
