# Generated by Django 6.0.5 on 2026-08-12 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0006_contest_contest_end_rating_and_more"),
        ("problems", "0006_problem_problem_created_at"),
        ("submissions", "0005_alter_submission_verdict"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["user", "problem"], name="sub_user_problem"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["problem", "verdict"], name="sub_problem_verdict"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["contest", "verdict"], name="sub_contest_verdict"
            ),
        ),
    ]
